name: bps
check_this_dir: /var/lib/bps
create_rootfs: debootstrap /target
install_package: bps -i {packages}
remove_package: bps -r {packages}
remove_package_with_unusing_deps: bps autoremove -r {packages}
remove_package_with_needed_packages: bps -r {packages}
full_system_update: chroot /target bps -u
